name: Bug report
description: Create a bug report to help us improve.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to fill out a bug report. Remember to fill out all fields including the title above. 
        An issue that is not properly filled out will be closed.
  - type: dropdown
    id: client
    attributes:
      label: What client do you play on?
      options:
      - enGB
      - enUS
      - deDE
      - esES
      - frFR
      - ruRU
      - other
    validations:
      required: true
  - type: checkboxes
    id: faction
    attributes:
      label: Faction
      options:
      - label: Alliance
      - label: Horde
  - type: checkboxes
    id: phase
    attributes:
      label: "Content Phase:"
      options:
      - label: Generic
      - label: 1-19
      - label: 20-29
      - label: 30-39
      - label: 40-49
      - label: 50-59
  - type: textarea
    id: current
    attributes:
      label: Current Behaviour
      description: |
        Describe the bug in detail. Database to link spells, NPCs, quests etc: https://wowgaming.altervista.org/aowow/
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Blizzlike Behaviour
      description: |
        Describe how it should be working without the bug. Link to evidence if possible such as YouTube videos or WoWHead comments from the time.
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: Source
      description: |
        HEADS UP: include sources in your bug report which are relevant to the 3.3.5a game version, 
        we will close any bug like "X should be changed to Y" reported without sources.
    validations:
      required: false
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the problem
      description: |
        Describe precisely how to reproduce the bug so we can fix it or confirm its existence:
        - Which commands to use? Which NPC to teleport to?
        - Do we need to have debug flags on Cmake?
        - Do we need to look at the console while the bug happens?
        - Other steps
        - Use the ingame commands to identify the unique GUID of an ore/herb/npc:    .npc info  /  .gobject near
      placeholder: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Extra Notes
      description: |
        Any information that can help the developers to identify and fix the issue should be put here.
        Examples:
        Links to items/NPCs/quests from https://wowgaming.altervista.org/aowow/
      placeholder: |
        None
    validations:
      required: false
  - type: textarea
    id: commit
    attributes:
      label: AC rev. hash/commit
      value: |
        https://github.com/chromiecraft/azerothcore-wotlk/commit/1f44732417968953c965e392c373cc453f79cf02
    validations:
      required: true
  - type: textarea
    id: os
    attributes:
      label: Operating system
      value: |
        Ubuntu 20.04
    validations:
      required: true
  - type: textarea
    id: modules
    attributes:
      label: Modules
      value: |
        - [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
        - [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
        - [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
        - [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
        - [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
        - [mod-eluna-lua-engine](https://github.com/azerothcore/mod-eluna-lua-engine)
        - [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
        - [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
        - [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
        - [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
        - [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
        - [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
        - [mod-server-auto-shutdown](https://github.com/azerothcore/mod-server-auto-shutdown)
        - [lua-carbon-copy](https://github.com/55Honey/Acore_CarbonCopy)
        - [lua-custom-corldboss](https://github.com/55Honey/Acore_CustomWorldboss)
        - [lua-level-up-reward](https://github.com/55Honey/Acore_LevelUpReward)
        - [lua-recruit-a-friend](https://github.com/55Honey/Acore_RecruitAFriend)
        - [lua-send-and-bind](https://github.com/55Honey/Acore_SendAndBind)
        - [lua-temp-announcements](https://github.com/55Honey/Acore_TempAnnouncements)
        - [lua-zonecheck](https://github.com/55Honey/acore_Zonecheck)
    validations:
      required: false
  - type: textarea
    id: customizations
    attributes:
      label: Customizations
      value: |
        None
    validations:
      required: false
  - type: textarea
    id: server
    attributes:
      label: Server
      value: |
        ChromieCraft
    validations:
      required: false
