name: Bug report
description: Create a bug report to help us improve.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to fill out a bug report. Remember to fill out all fields including the title above. 
        An issue that is not properly filled out will be closed.
  - type: textarea
    id: current
    attributes:
      label: Current Behaviour
      description: |
        Describe the bug in detail. Database to link spells, NPCs, quests etc: https://wowgaming.altervista.org/aowow/
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Blizzlike Behaviour
      description: |
        Describe how it should be working without the bug. Link to evidence if possible such as YouTube videos or Wowhead comments from the time.
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: Source
      description: |
        Provide us with source comments, videos, blue posts. Things officially confirm your issue. 
        Example: A video of showing how this NPC should behave in 3.3.5a version. 
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the problem
      description: |
        Describe precisely how to reproduce the bug so we can fix it or confirm its existence:
        - Which commands to use?
        - Which NPC to teleport to?
        - Other steps
        - Use the in-game commands to identify the unique GUID of an ore/herb/NPC:    .npcinfo  /  .gobject near
      placeholder: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Extra Notes
      description: |
        Any information that can help the developers to identify and fix the issue should be put here.
        Examples:
        Links to items/NPCs/quests from https://wowgaming.altervista.org/aowow/
      placeholder: |
        None
    validations:
      required: false
  - type: textarea
    id: commit
    attributes:
      label: AC rev. hash/commit
      value: |
       https://github.com/chromiecraft/azerothcore-wotlk/commit/ac6dea6df300c2fa48632429e36b93f2da60dd48
    validations:
      required: true
  - type: textarea
    id: os
    attributes:
      label: Operating system
      value: |
        Ubuntu 22.04
    validations:
      required: true
  - type: textarea
    id: modules
    attributes:
      label: Modules
      value: |
        - [mod-1v1-arena](https://github.com/azerothcore/mod-1v1-arena)
        - [mod-ah-bot](https://github.com/azerothcore/mod-ah-bot)
        - [mod-anticheat](https://github.com/azerothcore/mod-anticheat)
        - [mod-arena-3v3-solo-queue](https://github.com/azerothcore/mod-arena-3v3-solo-queue)
        - [mod-arena-replay](https://github.com/azerothcore/mod-arena-replay)
        - [mod-bg-item-reward](https://github.com/azerothcore/mod-bg-item-reward)
        - [mod-breaking-news-override](https://github.com/azerothcore/mod-breaking-news-override)
        - [mod-cfbg](https://github.com/azerothcore/mod-cfbg)
        - [mod-chat-transmitter](https://github.com/azerothcore/mod-chat-transmitter)
        - [mod-chromie-xp](https://github.com/azerothcore/mod-chromie-xp)
        - [mod-costumes](https://github.com/azerothcore/mod-costumes)
        - [mod-cta-switch](https://github.com/azerothcore/mod-cta-switch)
        - [mod-desertion-warnings](https://github.com/azerothcore/mod-desertion-warnings)
        - [mod-dmf-switch](https://github.com/azerothcore/mod-dmf-switch)
        - [mod-duel-reset](https://github.com/azerothcore/mod-duel-reset)
        - [mod-eluna](https://github.com/azerothcore/mod-eluna)
        - [mod-instanced-worldbosses](https://github.com/nyeriah/mod-instanced-worldbosses)
        - [mod-ip-tracker](https://github.com/azerothcore/mod-ip-tracker)
        - [mod-low-level-arena](https://github.com/azerothcore/mod-low-level-arena)
        - [mod-low-level-rbg](https://github.com/azerothcore/mod-low-level-rbg)
        - [mod-multi-client-check](https://github.com/azerothcore/mod-multi-client-check)
        - [mod-npc-spectator](https://github.com/gozzim/mod-npc-spectator)
        - [mod-progression-system](https://github.com/azerothcore/mod-progression-system)
        - [mod-pvp-titles](https://github.com/azerothcore/mod-pvp-titles)
        - [mod-pvpstats-announcer](https://github.com/azerothcore/mod-pvpstats-announcer)
        - [mod-queue-list-cache](https://github.com/azerothcore/mod-queue-list-cache)
        - [mod-rdf-expansion](https://github.com/azerothcore/mod-rdf-expansion)
        - [mod-transmog](https://github.com/azerothcore/mod-transmog)
        - [mod-weekend-xp](https://github.com/azerothcore/mod-weekend-xp)
        - [mod-zone-difficulty](https://github.com/azerothcore/mod-zone-difficulty)
        - [lua-CarbonCopy](https://github.com/55Honey/Acore_CarbonCopy)
        - [lua-eventScripts](https://github.com/55Honey/Acore_eventScripts)
        - [lua-ExchangeNpc](https://github.com/55Honey/Acore_ExchangeNpc)
        - [lua-LevelUpReward](https://github.com/55Honey/Acore_LevelUpReward)
        - [lua-RecruitAFriend](https://github.com/55Honey/Acore_RecruitAFriend)
        - [lua-SendAndBind](https://github.com/55Honey/Acore_SendAndBind)
        - [lua-TempAnnouncements](https://github.com/55Honey/Acore_TempAnnouncements)
        - [lua-Zonecheck](https://github.com/55Honey/acore_Zonecheck)
    validations:
      required: false
  - type: textarea
    id: customizations
    attributes:
      label: Customizations
      value: |
        None
    validations:
      required: false
  - type: textarea
    id: server
    attributes:
      label: Server
      value: |
        ChromieCraft
    validations:
      required: false
