name: Bug report
description: Create a bug report to help us improve.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking your time to fill out a bug report. Remember to fill out all fields including the title above. 
        An issue that is not properly filled out will be closed.
  - type: textarea
    id: current
    attributes:
      label: Current Behaviour
      description: |
        Describe the bug in detail. Database to link spells, NPCs, quests etc: https://wowgaming.altervista.org/aowow/
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Blizzlike Behaviour
      description: |
        Describe how it should be working without the bug. Link to evidence if possible such as YouTube videos or Wowhead comments from the time.
    validations:
      required: true
  - type: textarea
    id: source
    attributes:
      label: Source
      description: |
        Provide us with source comments, videos, blue posts. Things officially confirm your issue. 
        Example: A video of showing how this NPC should behave in 3.3.5a version. 
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce the problem
      description: |
        Describe precisely how to reproduce the bug so we can fix it or confirm its existence:
        - Which commands to use?
        - Which NPC to teleport to?
        - Other steps
        - Use the in-game commands to identify the unique GUID of an ore/herb/NPC:    .npcinfo  /  .gobject near
      placeholder: |
        1. 
        2. 
        3. 
        4.
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: Extra Notes
      description: |
        Any information that can help the developers to identify and fix the issue should be put here.
        Examples:
        Links to items/NPCs/quests from https://wowgaming.altervista.org/aowow/
      placeholder: |
        None
    validations:
      required: false
  - type: textarea
    id: customizations
    attributes:
      label: Customizations
      description: |
        Provide any additional customizations you may have, such as client patches.
      placeholder: |
        None
    validations:
      required: false
  - type: textarea
    id: commit
    attributes:
      label: AC rev. hash/commit
      value: |
       https://github.com/chromiecraft/azerothcore-wotlk/commit/6775478324934f9111f0f4d08b1ababcb8aa177a
      description: |
        This field is used for the triage process, you don't need to edit this!
    validations:
      required: true
